require('express-async-errors')
const express = require('express')
// const helmet = require("helmet")
const cors = require('cors')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const subscriberRoutes = require('./Routes/subscriber')
const memberRoutes = require('./Routes/member')
const eventRoutes = require('./Routes/event')
const userRoutes = require('./Routes/user')
const contactRoutes = require('./Routes/contact')
const companyRoutes = require('./Routes/company')
const middleware = require('./Utils/middleware')
require('dotenv').config()
const app = express()
app.use(bodyParser.json())
app.use(cookieParser())
app.use(bodyParser.urlencoded({
    extended: true
}))//["http://localhost:3000"]
app.use(cors({ origin: true, credentials: true }))
app.use('/Files', express.static('Files'))
app.use(express.json())
// app.use(helmet())
app.use(express.urlencoded({ extended: true }))
app.use(middleware.requestLogger)
app.use(middleware.userExtractor)
app.use('/api/subscribers', subscriberRoutes)
app.use('/api/hidden/subscribers', subscriberRoutes)
app.use('/api/members', memberRoutes)
app.use('/api/hidden/members', memberRoutes)
app.use('/api/events', eventRoutes)
app.use('/api/hidden/events', eventRoutes)
app.use('/api/hidden/users', userRoutes)
app.use('/api/contact', contactRoutes)
app.use('/api/hidden/company', companyRoutes)
app.use('/api/company', companyRoutes)
app.use(middleware.errorHandler)
app.use(middleware.unknownEndpoint)
module.exports = app